[dependencies]

  [package]
  cjc-version = "1.1.0"
  compile-option = "-O2 -Woff unused"
  name = "ahoCorasick4cj"
  organization = "cangjie_tpc"
  description = "字符串匹配算法库"
  version = "1.0.5"
  output-type = "dynamic"
  authors = []
  repository = "https://gitcode.com/Cangjie-TPC/ahocorasick4cj"
  homepage = "https://gitcode.com/Cangjie-TPC/ahocorasick4cj"
  documentation = "https://gitcode.com/Cangjie-TPC/ahocorasick4cj/blob/develop/doc/feature_api.md"
  tag = ["cangjie"]
  category = ["Utility"]
  license = ["Apache-2.0"]
  include = ["src"]
  exclude = []

[profile]
  [profile.build]
    incremental = true
    lto = ""
  [profile.customized-option]
    debug = "-g -Woff all -Won apilevel-check"
    release = "--fast-math -O2 -s -Woff all -Won apilevel-check"
  [profile.test]